name: offlineimap
version: git
summary: OfflineIMAP
description: |
  OfflineIMAP is software that downloads your email mailbox(es) as local
  Maildirs. OfflineIMAP will synchronize both sides via IMAP.

grade: devel
confinement: devmode

apps:
  offlineimap:
    command: bin/offlineimap

parts:
  setup:
    plugin: python
    python-version: python2
    python-packages: [six]
  offlineimap:
    after: [setup]
    plugin: python
    python-version: python2
    source: .
